Supershift/Sushi.Mediakiwi

src/Sushi.Mediakiwi/Framework/ListDataColumns.cs
src/Sushi.Mediakiwi/Utils.cs

These changes are made in this PR 
- Fixed Highlight column check
- Utils class cleanup

Fixed Highlight column check

---

src/Sushi.Mediakiwi/PageModules/ExportPage/ExportPageModule.cs

The fixed bug was that the JSON output was writting to the response, but was also extended with the page HTML content, so offered a download link to download the JSON contents

Translated page exporter to EN and fixed a bug

---

src/Sushi.Mediakiwi/Utils.cs

causing the response to always be HtmlEncoded

The returnHtmlEncodedResponse parameter was ignored

---

src/Sushi.Mediakiwi.Data/Data/Asset.cs
src/Sushi.Mediakiwi.Data/Data/Gallery.cs

Some missing Async methods were found

Found some missing Async methods

---

src/Sushi.Mediakiwi.Demonstration/Templates/List/DemoList2.cs
src/Sushi.Mediakiwi.Demonstration/appsettings.json
src/Sushi.Mediakiwi/Cms/Console.cs
src/Sushi.Mediakiwi/Extention/ComponentListExtension.cs
src/Sushi.Mediakiwi/UI/DataGrid.cs
src/Sushi.Mediakiwi/UI/Monitor.cs
src/Sushi.Mediakiwi/Utils.cs

Expose the option to get a listitemcollection based on listSearch for a dropdown.

Get listcollection from within another list.

---

src/Sushi.Mediakiwi.Demonstration/Templates/List/DemoList3.cs
src/Sushi.Mediakiwi.Demonstration/Templates/List/DemoList4.cs
src/Sushi.Mediakiwi/Framework/ContentListItem/DataListAttribute.cs
src/Sushi.Mediakiwi/UI/DataGrid.cs
src/Sushi.Mediakiwi/UI/Monitor.cs

Check out Demolist 4 for a reproduction path

See the explanations on DemoList4

---

src/Sushi.Mediakiwi.Data/Data/AvailableTemplate.cs

This caused the creation of unneeded componentversions.
For every AvailableTemplate coupled to the PageTemplate a new ComponentVersion would be created on every page visit

A missing where clause in the AvailableTemplate class

---

src/Sushi.Mediakiwi.Data/Data/Link.cs
src/Sushi.Mediakiwi/AppCentre/UI/Link.cs
src/Sushi.Mediakiwi/Cms/Component.cs
src/Sushi.Mediakiwi/UI/Monitor.cs

sorted, also added disappeared delete (?). Only "<script>parent.removeLink();</script>" does not clear it's parent. Can you review?

Link is removed

---

src/Sushi.Mediakiwi.Data/Configuration/WimServerConfiguration.cs
src/Sushi.Mediakiwi.Demonstration/appsettings.json
src/Sushi.Mediakiwi/Framework/Functions/DatabaseCompare.cs
src/Sushi.Mediakiwi/Portal.cs

applied optional installation to assure the actions (irrevocable) to be excluded.

applied optional installation

---

src/Sushi.Mediakiwi.Data/Common.cs
src/Sushi.Mediakiwi.Headless/Common.cs
src/Sushi.Mediakiwi.Headless/Utilities/Visitor.cs
src/Sushi.Mediakiwi/Authentication/Authentication.cs
src/Sushi.Mediakiwi/Identity/VisitorManager.cs
src/Sushi.Mediakiwi/Utilities/EncryptionByRijndael.cs

added the following discovery flow:
1. User-Agent
2. Request-Id
3. Host
4. Encryption key
Added a Common to the Headless project as well.
TODO Follow-up tasks :
1. Clean up configuration settings, we have too much of them:
- Common
- CommonConfiguration
- WimServerSettings
These need to be combined into one.
Then de encryption key needs to move to the appropriate spot in appsettings and be read into the config

Added fallbacks

---

src/Sushi.Mediakiwi/Framework/PagePreview.cs
src/Sushi.Mediakiwi/Presentation/Logic/Navigation.cs

Original issue description:
'Aanmaken van nieuwe pagina's in MK geeft error na opslaan (InvalidOperationException: Nullable object must have a value.)'
I also noticed there was a server error when deleting a page. I have solved that in this branch as well.

page-save-InvalidOperationException

---

src/Sushi.Mediakiwi/Logic/OAuth2Logic.cs
src/Sushi.Mediakiwi/UI/Monitor.cs

Look for other claims if expected claim is not found

active-directory-logging

---

src/Sushi.Mediakiwi.Data/Data/Folder.cs
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi/AppCentre/UI/Forms/SiteForm.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

Restored missing Join on folders

Restored Channel Homepage

---

src/Sushi.Mediakiwi/AppCentre/UI/RoleAccessList.cs
src/Sushi.Mediakiwi/Cms/Component.cs
src/Sushi.Mediakiwi/Cms/Data/Component.cs
src/Sushi.Mediakiwi/Framework/ContentInfoItem/Binary_DocumentAttribute.cs
src/Sushi.Mediakiwi/Framework/ContentInfoItem/ContentSharedAttribute.cs
src/Sushi.Mediakiwi/Framework/ContentInfoItem/MultiFieldAttribute.cs
src/Sushi.Mediakiwi/Framework/MetaData.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

- Various fixes for dropdown initialization.
- Fix for Shared Document

Various fixes for dropdown initialization.

---

src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Framework/ContentInfoItem/ContentSharedAttribute.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

- Sublist 'T' replacement fix (this would replace every 'T' present in the Sublist title)
- Some code cleanup

Sublist 'T' replacement fix

---

src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Headless/BaseRazorComponent.cs
src/Sushi.Mediakiwi.Headless/BaseRazorPage.cs
src/Sushi.Mediakiwi.Headless/BaseRazorPageLayout.cs
src/Sushi.Mediakiwi.Headless/BaseRazorPageModel.cs
src/Sushi.Mediakiwi.Headless/MediaKiwiContentService.cs
src/Sushi.Mediakiwi.Headless/MediaKiwiRewriteRule.cs
src/Sushi.Mediakiwi.Headless/MetaTagHelperComponent.cs
src/Sushi.Mediakiwi.Headless/SlotTagHelper.cs
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

When the Cache validator states a flush is needed, 
this is now passed along the components within the page

Updated cache flush determination

---

src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Framework/ContentInfoItem/Choice_DropdownAttribute.cs
src/Sushi.Mediakiwi/Framework/ContentInfoItem/Choice_RadioAttribute.cs
src/Sushi.Mediakiwi/Framework/ContentInfoItem/ContentSharedAttribute.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

The autopostback classname was accidentally removed from the RadioButton and is restored in this branch

The RadioButton postback option didn't work

---

src/Sushi.Mediakiwi.API/Extensions/Extensions.cs
src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj

Changes in this Commit:
- Removed obsolete package
- Changed copy for xml

XML not visible

---

src/Sushi.Mediakiwi.API/Extensions/Extensions.cs
src/Sushi.Mediakiwi.API/Middleware/ApiCorsMiddleware.cs
src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj

Cookie policy for API adjusted
CORS policy for API adjusted

Policies adjusted

---

src/Sushi.Mediakiwi.API/Controllers/Content.cs
src/Sushi.Mediakiwi.API/Controllers/Navigation.cs
src/Sushi.Mediakiwi.API/Transport/AuthenticatedRequest.cs
src/Sushi.Mediakiwi.API/Transport/Requests/GetTopNavigationRequest.cs

The GET methods were reading the Request object from the Body, which isn't supported in all cases.
Now they are read from the QueryString

GET methods read arguments from Query

---

src/Sushi.Mediakiwi.API/Filters/MediakiwiConsoleFilter.cs
src/Sushi.Mediakiwi.Demonstration/Templates/List/DemoList1.cs
src/Sushi.Mediakiwi/AppCentre/UI/DocumentType_List.cs
src/Sushi.Mediakiwi/AppCentre/UI/RoleAccessSite.cs
src/Sushi.Mediakiwi/Cms/Console.cs
src/Sushi.Mediakiwi/Extention/ComponentListExtension.cs
src/Sushi.Mediakiwi/Framework/AdditionalResource.cs
src/Sushi.Mediakiwi/Framework/ComponentListTemplate.cs
src/Sushi.Mediakiwi/Framework/Interfaces/iRouting.cs
src/Sushi.Mediakiwi/Framework/WimComponentListRoot.cs
src/Sushi.Mediakiwi/Portal.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj
src/Sushi.Mediakiwi/UI/Monitor.cs

Fixed the following issues :
- ComponentListRouting didn't work
- Replaced IHostingEnvironment (marked obsolete) with IHostEnvironment
- User list displayed the users role incorrect 
Introduced the following features :
- Asynchronous adding of resources to a Component List
- ComponentListRouting classes can contain a constructor with IServiceProvider

Fixed some issues that came to light when using net 6.0

---

src/Sushi.Mediakiwi.API/Extensions/Extensions.cs
src/Sushi.Mediakiwi.API/Filters/MediakiwiConsoleFilter.cs
src/Sushi.Mediakiwi.API/Services/ContentService.cs
src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.API/Transport/ContentField.cs
src/Sushi.Mediakiwi.API/Transport/Responses/GetListResponse.cs
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Framework/WimComponentListRoot.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj
src/Sushi.Mediakiwi/Utilities/Mail.cs

Most notable changes in this PR:
- Removed internal API querystring from list context
- Added Row URL for grid rows
- Added LayerConfig for grid

Various API changes

---

src/Sushi.Mediakiwi.Data/Configuration/WimServerConfiguration.cs
src/Sushi.Mediakiwi.Demonstration/appsettings.json
src/Sushi.Mediakiwi/CommonConfiguration.cs
src/Sushi.Mediakiwi/Presentation/Monitor.cs

Add custom stylesheet though appsettings and keep the existing styles.min.css on the page

Append stylesheet

---

src/Sushi.Mediakiwi.API/Controllers/Content.cs
src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

Depending on whether or not we're posting to an Item or an overview,
we should differentiate the View type for the Console, so that properties will be resolved correctly

Set correct View to Console for Save/Browse mode

---

src/Sushi.Mediakiwi.API/Controllers/Navigation.cs
src/Sushi.Mediakiwi.API/Services/INavigationService.cs
src/Sushi.Mediakiwi.API/Services/NavigationService.cs
src/Sushi.Mediakiwi/Cms/UrlBuilder.cs
src/Sushi.Mediakiwi/Interfaces/iPresentationNavigation.cs
src/Sushi.Mediakiwi/Presentation/Logic/Navigation.cs
src/Sushi.Mediakiwi/Presentation/Monitor.cs
src/Sushi.Mediakiwi/UI/Monitor.cs

A few changes in this PR, namely:
- Changed Logo homepage Link
- Changed redirect after login
- Replaced Double starting slash for URLs by one starting slash
- Replaced some methods to be Asynchronous

Changed Logo homepage Link

---

src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj

so it won't conflic with the generated output xml

Set Sushi.Mediakiwi.API.xml as Documentation File 

---

src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.API/UrlResolver.cs
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Data/PageContentResponse.cs
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Cms/Console.cs
src/Sushi.Mediakiwi/Controllers/ContentController.cs
src/Sushi.Mediakiwi/Controllers/Data/PageContentResponse.cs
src/Sushi.Mediakiwi/Logic/PageLogic.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

Added NullCheck to some URL string checks
Increased MK version

Added ChannelID to PageContentResponse.

---

src/Sushi.Mediakiwi.Demonstration/Templates/List/DemoList1.cs
src/Sushi.Mediakiwi.Demonstration/Templates/List/DemoList2.cs
src/Sushi.Mediakiwi/Cms/Console.cs
src/Sushi.Mediakiwi/UI/Monitor.cs

This depends on:
- HostingEnvironment (when this is 'Development' the full exception is shown, else a summary is shown)
- Is_Local_development (when this is 'true' the summary is detailed, else it's concise)

Added global exception handler

---

src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

MK Version increase

---

src/Sushi.Mediakiwi.API/Controllers/Navigation.cs
src/Sushi.Mediakiwi.API/Transport/Requests/GetTopNavigationRequest.cs
src/Sushi.Mediakiwi.Data/Data/Interfaces/IMenu.cs
src/Sushi.Mediakiwi.Data/Data/Menu.cs
src/Sushi.Mediakiwi.Data/Data/MenuGroup.cs
src/Sushi.Mediakiwi.Data/Data/MenuItemView.cs
src/Sushi.Mediakiwi/AppCentre/UI/MenuGroupList.cs
src/Sushi.Mediakiwi/AppCentre/UI/MenuList.cs
src/Sushi.Mediakiwi/Framework/ContentListItem/ButtonAttribute.cs
src/Sushi.Mediakiwi/Resources/sql_data.sql
src/Sushi.Mediakiwi/Resources/sql_tables.sql
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj
src/Sushi.Mediakiwi/UI/Monitor.cs

Added Menu Groups list to MediaKiwi, which allows for menu's to be attached to a Menu Group.
The GroupTag can then be used in the MKAPI to retrieve the correct Menu

Added Menu Groups option

---

src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Common.cs
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/CommonConfiguration.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

Changes:
- Added NULL checks to the **WimServerConfiguration.Instance** property
- Updated MK version

Additional NULL check for config instance

---

src/Sushi.Mediakiwi.Demonstration/Properties/launchSettings.json
src/Sushi.Mediakiwi.Demonstration/Templates/List/DemoList2.cs
src/Sushi.Mediakiwi.Demonstration/Templates/List/Maps/DemoList2Map.cs
src/Sushi.Mediakiwi/Framework/ContentInfoItem/Choice_DropdownAttribute.cs
src/Sushi.Mediakiwi/Framework/ContentInfoItem/Choice_RadioAttribute.cs

Fixed two issues:
- The returntype was **undefined** for Radio's
- For Multi select dropdowns the returntype was Dropdown, instead of MultiSelect Dropdown

Fixed the returning VueType for Dropdown and Radio

---

src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Framework/ContentInfoItem/Choice_DropdownAttribute.cs
src/Sushi.Mediakiwi/Framework/ContentInfoItem/Choice_RadioAttribute.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

- Return options for Radio Filters
- Fixed Array determination (string was seen as array)

Fixed two filter related issues

---

src/Sushi.Mediakiwi.API/Authentication/MediakiwiCookieValidator.cs
src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Cms/Console.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

So fallback to the user on the list when needed.
This was due to a change to the Console.CurrentApplicationUser getter from within the AAD adjustment

In some cases the User exists on the List, but not on the Console

---

src/Sushi.Mediakiwi.API/Extensions/Extensions.cs
src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Framework/ContentInfoItem/Binary_ImageAttribute.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

The following fixes were done in this PR:
- Fixed posting an Image ID with the API
- Fixed DateTime field posting with the API

Two fixes targeting the API

---

src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Demonstration/Properties/launchSettings.json
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Framework/ContentInfoItem/Binary_DocumentAttribute.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

Whenever a post was done with the document field in the form with the MKAPI, it wasn't retrieved.
Same fix was done for the Image field last week

Document type field post not retrieved

---

src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Extention/ComponentListExtension.cs
src/Sushi.Mediakiwi/Framework/Interfaces/iRouting.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

This change enables the Validate Method to receive an HttpContext so that additional querystring can be checked.

The HttpContext is passed along with the ComponentlistRouting

---

src/Sushi.Mediakiwi.API/Services/UserService.cs
src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

The API was unaware of visitor entity, i added some logic to be able to use a visitor

Set visitor Cookie in API

---

src/Sushi.Mediakiwi.API/Services/ContentService.cs
src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

When a formfield is Datalist, there will be a Grid added to the API output

DataList added to API as Grid 

---

src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.API/UrlResolver.cs
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

the folder will be taken into account

When a list title has multiple matches

---

src/Sushi.Mediakiwi.API/Controllers/Navigation.cs
src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

There was an issue with the **isSelected** property, this property wasn't reset correctly, so it remained True, causing all following submenu items to be highlighted

Menu items highlighting fix

---

src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi.Logic/Sushi.Mediakiwi.Logic.csproj
src/Sushi.Mediakiwi.Website/Properties/launchSettings.json
src/Sushi.Mediakiwi.Website/Startup.cs
src/Sushi.Mediakiwi.Website/Sushi.Mediakiwi.Website.csproj.user
src/Sushi.Mediakiwi.Website/appsettings.json
src/Sushi.Mediakiwi/Controllers/ContentController.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

fix for this issue : https://supershift.atlassian.net/browse/MK-35

Apply Richtext link added to Headless Content API

---

src/Sushi.Mediakiwi.API/Common.cs
src/Sushi.Mediakiwi.API/Filters/MediakiwiConsoleFilter.cs
src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi.Logic/Sushi.Mediakiwi.Logic.csproj
src/Sushi.Mediakiwi/Framework/WimComponentListRoot.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

Added the following features:
- Method to clear the grid.
- Property to determine if the call was made by the MKAPI

Two features added

---

src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/AppCentre/UI/MenuList.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

The menu delete button didn't delete the menu itself,

---

src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi/Cms/UrlBuilder.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj
src/Sushi.Mediakiwi/UI/Monitor.cs

When landing on the Root URL, lookup correct menu for redirection to homepage.

Redirect on channel switch

---

src/Sushi.Mediakiwi.API/Sushi.Mediakiwi.API.csproj
src/Sushi.Mediakiwi.Data.Elastic/Sushi.Mediakiwi.Data.Elastic.csproj
src/Sushi.Mediakiwi.Data/Sushi.Mediakiwi.Data.csproj
src/Sushi.Mediakiwi.Elastic.UI/Sushi.Mediakiwi.Elastic.UI.csproj
src/Sushi.Mediakiwi.Headless/Sushi.Mediakiwi.Headless.csproj
src/Sushi.Mediakiwi.Logic/Sushi.Mediakiwi.Logic.csproj
src/Sushi.Mediakiwi/Cms/Console.cs
src/Sushi.Mediakiwi/Sushi.Mediakiwi.csproj

when converting an int array for multiselect
